Jokes = {
    "1": "What's a computer's favorite snack? Microchips!",
    "2": "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
    "3": "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "4": "What do you call fake spaghetti? An impasta!",
    "5": "How does a penguin build its house? Igloos it together!",
    "6": "What do you call an alligator in a vest? An investigator!",
    "7": "What do you call a bear with no teeth? A gummy bear!",
    "8": "Why couldn't the bicycle stand up by itself? Because it was two-tired!",
    "9": "Never trust an atom. They make up everything!",
    "10": "Did you hear about the kidnapping at the playground? Don't worry, they woke up!",
    "11": "My wife told me to put ketchup on the shopping list. Now I can't read anything",
    "12": "I have a fear of speedbumps, but I'm slowly getting over it.",
    "13": "My coworkers voted me the most secritive gy in the office. I can't tell you how much this means to me.",
    "14": "I had to fire the guy I hired to mow my lawn. He just didn't cut it.",
    "15": "I figured out why Teslas are so expensive. It's because they charge a lot.",
}

Facts = {
    "1": "Despite popular belief, astronauts can't see the great wall of china without aid.",
    "2": "Polar bears are nearly undetectable by infrared cameras: Their fur i so effective at trapping heat that they are almost invisible in the cold.",
    "3": "Fun fact! A shrimp's heart is in its head.",
    "4": "The shortest commercial flight in the world lasts only 1.5 minutes: It's the flight between the Scottish islands of Westray and Papa Westray.",
    "5": "The oldest \"your mom\" joke was discovered on a 3,500-year-old Babylonian tablet.",
    "6": "The shortest war in history lasted only 38 minutes.",
    "7": "The Earth's deepest point is deeper than Mount Everest is tall.",
    "8": "There are more possible iterations of a game of chess than there are atoms in the observable universe.",
    "9": "Fun Fact! A day on Venus is longer than a year on Venus.",
    "10": "Fun Fact! The world's largest snowflake was 15 inches wide.",
}

Knowledge = {
    "sing": "Sorry, but I can't sing",
    "homework": "Sorry, but I can't do homework",
    "Who made you": "I was created by Horizon Technologies",
    "who made you": "I was created by Horizon Technologies",
    "your name": "I am HorizonAI",
    "people in the world": "as of my last update in November 2024, there are 8.2 billion people in the world.",
    "feet are in a mile": "There are 5280 feet in a mile",
    "feet in a mile": "There are 5280 feet in a mile",
    "you perfect": "I am not perfect",
    "days are in a year": "There are 365 days in a year",
    "days in a year": "There are 365 days in a year",
    "do math": "I can do math, just give me an equation",
    "What are you": "I am a pesonal assistant created by Horizon Technologies",
    "what are you": "I am a pesonal assistant created by Horizon Technologies",
    "dumb": "I am new and still learning. Ask me something and I will answer it as best as I can",
    "stupid": "I am new and still learning. Ask me something and I will answer it as best as I can",
    "your favorite food": "As a series of code, I can't have a favorite food",
    "you alive": "As a series of code, I am not alive",
    "you have feelings": "I am unable to express feelings",
    "ounces in a cup": "There are 8 ounces in a cup",
    "When is daylight savings time": "Daylight saving time always starts on the second Sunday in March and ends on the first Sunday in November for the United States",
    "when is daylight savings time": "Daylight saving time always starts on the second Sunday in March and ends on the first Sunday in November for the United States",
    "What is daylight savings time": "Daylight savings is a way for people to make more use of daylight by shifting the time",
    "what is daylight savings time": "Daylight savings is a way for people to make more use of daylight by shifting the time",
    "Why is the sky blue": "Blue light is scattered in all directions by the tiny molecules of air in Earth's atmosphere. Blue is scattered more than other colors because it travels a shorter distance",
    "why is the sky blue": "Blue light is scattered in all directions by the tiny molecules of air in Earth's atmosphere. Blue is scattered more than other colors because it travels a shorter distance",
    "save money": "You can save money by putting some off to spend and some into a savings account each time you get paid",
    "make money": "You can make money by walking dogs or mowing lawns",
    "meaning of life": "Although it differs for everyone, the meaning of life can be finding fufulment and contentment",
    "backup iphone": "You can back up your iphone by going to settings -> iCloud -> iCloud Backup",
    "backup my iphone": "You can back up your iphone by going to settings -> iCloud -> iCloud Backup",
    "bored": "If you're bored, try going for a walk, reading, or completing a puzzle",
    "old is earth": "The Earth is 4.543 billion years old",
    "old is the earth": "The Earth is 4.543 billion years old",
    "is a meme": "A meme is an image or video, usually humorous, that is spead across the internet",
    "earth made": "The Earth was made 4.543 billion years ago",
    "aliens real": "As far as I know, aliens do not exist. However it is likely",
    "aliens exist": "As far as I know, aliens do not exist. However it is likely",
    "you worried about": "I am not worried about anything",
    "Write me an email": "Sorry, but I can't write an email",
    "write me an email": "Sorry, but I can't write an email",
    "Write an email": "Sorry, but I can't write an email",
    "Write an email": "Sorry, but I can't write an email",
    "assist me": "Assisting others is something I'm great at! Ask me anything and I'll help as best as I can",
    "Thanks": "You're welcome",
    "thanks": "You're welcome",
    "Thank you": "You're welcome",
    "thank you": "You're welcome",
    "directions": "Sorry, but I don't have access to mapping services",
    "map": "Sorry, but I don't have access to mapping services",
    "color is the sun": "The sun is yellow and orange",
    "color is the sky": "The sky is usually blue due to the scattering of sunlight by the atmosphere, though it can appear red, orange, or purple at sunrise and sunset.",
    "color of the sky": "The sky is typically blue, but it can change to colors like red or pink at dawn and dusk.",
    "color is grass": "Grass is usually green due to the presence of chlorophyll, which helps it absorb sunlight.",
    "color of grass": "Grass is primarily green, thanks to chlorophyll, the pigment involved in photosynthesis.",
    "color is snow": "Snow appears white because it reflects most of the visible light that hits it.",
    "color of snow": "Snow looks white, as its structure reflects light across the entire visible spectrum.",
    "color is the ocean": "The ocean often appears blue because water absorbs colors in the red part of the light spectrum, leaving blue to be reflected back to our eyes.",
    "color of the ocean": "The ocean typically looks blue, although it can appear green or even gray depending on the surroundings and lighting.",
    "color is a banana": "A ripe banana is usually yellow, though it starts out green and can turn brown as it over-ripens.",
    "color of a banana": "Bananas are usually yellow when ripe, but green when unripe and brown when overripe.",
    "color is an apple": "Apples come in various colors, including red, green, and yellow, depending on the type.",
    "color of an apple": "Apples can be red, green, or yellow, with each color indicating a different variety and flavor.",
    "color is the sun": "From Earth, the sun appears yellow due to atmospheric scattering, but it is actually white when viewed from space.",
    "color of the sun": "The sun looks yellow from Earth, but in reality, it emits white light across the full spectrum.",
    "color is the moon": "The moon appears gray and white, though it can look orange or red during certain phases like a lunar eclipse.",
    "color of the moon": "The moon’s surface is mostly gray and white, though it can take on colors like red during a lunar eclipse.",
    "color is sand": "Sand is often light brown or tan, though it can also be white, black, or pink depending on its mineral content.",
    "color of sand": "Sand is commonly tan or light brown, but it can vary from white to black or pink depending on location and minerals.",
    "color is blood": "Blood is red due to the presence of hemoglobin, which binds with oxygen.",
    "color of blood": "Blood is red, a result of oxygenated hemoglobin in our red blood cells.",
    "color are clouds": "Clouds are typically white or gray, depending on how much sunlight they reflect or block.",
    "color of clouds": "Clouds usually appear white, but they can look gray or even black during storms.",
    "color is fire": "Fire is typically yellow, orange, or red, but it can be blue, green, or even white, depending on temperature and materials burning.",
    "color of fire": "Fire is often orange or yellow, though it can vary from blue to white depending on its temperature and fuel source.",
    "color is coal": "Coal is black because it is a carbon-rich material formed from ancient plant matter.",
    "color of coal": "Coal is typically black, though it may have a slight sheen due to its mineral content.",
    "color is copper": "Freshly exposed copper has a reddish-brown color, though it can turn green over time as it oxidizes.",
    "color of copper": "Copper is naturally reddish-brown, but it develops a green patina with age and exposure to the elements.",
    "color is gold": "Gold has a distinctive yellow hue, making it unique among metals.",
    "color of gold": "Gold is yellow and shiny, valued for its rarity and attractive color.",
    "color is a tiger": "A tiger is orange with black stripes, which helps it blend into the forest or grasslands.",
    "color of a tiger": "Tigers have an orange coat with black stripes and a white underside, aiding in camouflage.",
    "color is lava": "Lava is typically bright orange or red when it’s hot, cooling to black as it solidifies.",
    "color of lava": "Lava is red or orange when molten, but it turns black or dark gray as it cools and hardens.",
    "color is chocolate": "Chocolate is usually brown, though white chocolate is cream-colored, and dark chocolate can be almost black.",
    "color of chocolate": "Chocolate is typically brown, ranging from light to dark, with white chocolate being cream-colored.",
    "color is a panda": "Pandas are black and white, with distinctive black patches around their eyes, ears, and limbs.",
    "color of a panda": "A panda has a unique black-and-white color pattern, with black around its eyes and on its limbs.",
    "color is water": "Pure water is clear, but it can look blue when viewed in large quantities because it absorbs red wavelengths.",
    "color of water": "Water is transparent, but it appears blue in large bodies due to light absorption and scattering.",
    "color is a tree": "A tree can be many colors depending on the type and season, but they are usually green",
    "color are trees": "A tree can be many colors depending on the type and season, but they are usually green",
    "What can you do": "I can do math, tell the date and time, tell a joke, a fact, and so much more",
    "what can you do": "I can do math, tell the date and time, tell a joke, a fact, and so much more",
    "digits of pi": "The first 12 digits of pi are 3.14159265359",
    "how are rainbows formed": "Rainbows are formed when light is refracted, or bent, as it passes through water droplets in the atmosphere, creating a spectrum of colors.",
    "why do we dream": "Dreams may help process emotions, consolidate memories, and simulate events. The exact reason is still a mystery to scientists.",
    "why is water wet": "Water is perceived as wet because it creates a sensation of wetness when it comes in contact with the skin.",
    "why is the ocean salty": "The ocean is salty due to minerals and salts that are washed away from rocks on land and carried by rivers to the sea.",
    "why do we yawn": "Yawning helps cool the brain and increases oxygen intake. It often happens when you're tired or bored.",
    "How are rainbows formed": "Rainbows are formed when light is refracted, or bent, as it passes through water droplets in the atmosphere, creating a spectrum of colors.",
    "Why do we dream": "Dreams may help process emotions, consolidate memories, and simulate events. The exact reason is still a mystery to scientists.",
    "Why is water wet": "Water is perceived as wet because it creates a sensation of wetness when it comes in contact with the skin.",
    "Why is the ocean salty": "The ocean is salty due to minerals and salts that are washed away from rocks on land and carried by rivers to the sea.",
    "Why do we yawn": "Yawning helps cool the brain and increases oxygen intake. It often happens when you're tired or bored.",
    "save energy": "You can save energy by turning off lights when you leave a room, unplugging devices not in use, and using energy-efficient appliances.",
    "lose weight": "You can lose weight by eating a balanced diet, exercising regularly, and getting enough sleep. Consulting a healthcare professional is also advised.",
    "gain muscle": "To gain muscle, follow a strength-training regimen, eat protein-rich foods, and ensure you're getting enough calories and rest.",
    "improve memory": "You can improve memory by engaging in mental exercises, maintaining a healthy diet, staying physically active, and getting plenty of sleep.",
    "relieve stress": "Relieve stress by practicing mindfulness, exercising, meditating, and connecting with friends and family.",
    "what is AI": "AI, or Artificial Intelligence, refers to machines programmed to simulate human intelligence, including learning, reasoning, and problem-solving.",
    "What is AI": "AI, or Artificial Intelligence, refers to machines programmed to simulate human intelligence, including learning, reasoning, and problem-solving.",
    "the sun hot": "The sun is hot because of nuclear fusion, where hydrogen atoms fuse into helium under immense pressure and heat, releasing energy.",
    "benefits of exercise": "Exercise improves physical health, boosts mood, reduces stress, and supports cognitive functions.",
    "importance of sleep": "Sleep is vital for restoring the body, consolidating memories, and supporting mental and physical health.",
    "tall is Mount Everest": "Mount Everest is 8,848 meters, or 29,029 feet, tall.",
    "far is the moon": "The average distance from Earth to the Moon is about 384,400 kilometers, or 238,855 miles.",
    "the biggest planet": "The largest planet in our solar system is Jupiter.",
    "old is the universe": "The universe is estimated to be about 13.8 billion years old.",
    "what is bitcoin": "Bitcoin is a digital currency that allows peer-to-peer transactions over a decentralized network.",
    "What is bitcoin": "Bitcoin is a digital currency that allows peer-to-peer transactions over a decentralized network.",
    "what is cryptocurrency": "Cryptocurrency is a digital or virtual currency that uses cryptography for security and operates on a decentralized network.",
    "what is cryptocurrency": "Cryptocurrency is a digital or virtual currency that uses cryptography for security and operates on a decentralized network.",
    "speed of light": "The speed of light in a vacuum is approximately 299,792 kilometers per second, or about 186,282 miles per second.",
    "long is a marathon": "A marathon is 26.2 miles or 42.195 kilometers.",
    "the tallest building": "The tallest building in the world is the Burj Khalifa in Dubai, which is 828 meters tall.",
    "how does photosynthesis work": "Photosynthesis is a process where plants convert sunlight, water, and carbon dioxide into oxygen and glucose for energy.",
    "how many continents are there": "There are seven continents: Africa, Antarctica, Asia, Europe, North America, Australia, and South America.",
    "How does photosynthesis work": "Photosynthesis is a process where plants convert sunlight, water, and carbon dioxide into oxygen and glucose for energy.",
    "How many continents are there": "There are seven continents: Africa, Antarctica, Asia, Europe, North America, Australia, and South America.",
}
