Jokes = {
    "1": "What's a computer's favorite snakc? Microchips!",
    "2": "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
    "3": "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "4": "What do you call fake spaghetti? An impasta!",
    "5": "How does a penguin build its house? Igloos it together!",
    "6": "What do you call an alligator in a vest? An investigator!",
    "7": "What do you call a bear with no teeth? A gummy bear!",
    "8": "Why couldn't the bicycle stand up by itself? Because it was two-tired!",
    "9": "Never trust an atom. They make up everything!",
    "10": "Did you hear about the kidnapping at the playground? Don't worry, they woke up!",
    "11": "My wife told me to put ketchup on the shopping list. Now I can't read anything",
    "12": "I have a fear of speedbumps, but I'm slowly getting over it.",
    "13": "My coworkers voted me the most secritive gy in the office. I can't tell you how much this means to me.",
    "14": "I had to fire the guy I hired to mow my lawn. He just didn't cut it.",
    "15": "I figured out why Teslas are so expensive. It's because they charge a lot.",
}

Facts = {
    "1": "Despite popular belief, astronauts can't see the great wall of china without aid.",
    "2": "Polar bears are nearly undetectable by infrared cameras: Their fur i so effective at trapping heat that they are almost invisible in the cold.",
    "3": "Fun fact! A shrimp's heart is in its head.",
    "4": "The shortest commercial flight in the world lasts only 1.5 minutes: It's the flight between the Scottish islands of Westray and Papa Westray.",
    "5": "The oldest \"your mom\" joke was discovered on a 3,500-year-old Babylonian tablet.",
    "6": "The shortest war in history lasted only 38 minutes.",
    "7": "The Earth's deepest point is deeper than Mount Everest is tall.",
    "8": "There are more possible iterations of a game of chess than there are atoms in the observable universe.",
    "9": "Fun Fact! A day on Venus is longer than a year on Venus.",
    "10": "Fun Fact! The world's largest snowflake was 15 inches wide.",
}

Knowledge = {
    "sing": "Sorry, but I can't sing",
    "homework": "Sorry, but I can't do homework",
    "Who made you": "I was created by Horizon Technologies",
    "who made you": "I was created by Horizon Technologies",
    "your name": "I am HorizonAI",
    "people in the world": "as of my last update in November 2024, there are 8.2 billion people in the world.",
    "feet are in a mile": "There are 5280 feet in a mile",
    "feet in a mile": "There are 5280 feet in a mile",
    "you perfect": "I am not perfect",
    "days are in a year": "There are 365 days in a year",
    "days in a year": "There are 365 days in a year",
    "do math": "I can do math, just give me an equation",
    "What are you": "I am a pesonal assistant created by Horizon Technologies",
    "what are you": "I am a pesonal assistant created by Horizon Technologies",
    "dumb": "I am new and still learning. Ask me something and I will answer it as best as I can",
    "stupid": "I am new and still learning. Ask me something and I will answer it as best as I can",
    "your favorite food": "As a series of code, I can't have a favorite food",
    "you alive": "As a series of code, I am not alive",
    "you have feelings": "I am unable to express feelings",
    "ounces in a cup": "There are 8 ounces in a cup",
    "the weather": "Sorry, I don't currently have access to the weather",
    "temp": "Sorry, I dont' currently have access to the weather",
    "When is daylight savings time": "Daylight saving time always starts on the second Sunday in March and ends on the first Sunday in November for the United States",
    "when is daylight savings time": "Daylight saving time always starts on the second Sunday in March and ends on the first Sunday in November for the United States",
    "What is daylight savings time": "Daylight savings is a way for people to make more use of daylight by shifting the time",
    "what is daylight savings time": "Daylight savings is a way for people to make more use of daylight by shifting the time",
    "Why is the sky blue": "Blue light is scattered in all directions by the tiny molecules of air in Earth's atmosphere. Blue is scattered more than other colors because it travels a shorter distance",
    "why is the sky blue": "Blue light is scattered in all directions by the tiny molecules of air in Earth's atmosphere. Blue is scattered more than other colors because it travels a shorter distance",
    "save money": "You can save money by putting some off to spend and some into a savings account each time you get paid",
    "make money": "You can make money by walking dogs or mowing lawns",
    "meaning of life": "Although it differs for everyone, the meaning of life can be finding fufulment and contentment",
    "backup iphone": "You can back up your iphone by going to settings -> iCloud -> iCloud Backup",
    "backup my iphone": "You can back up your iphone by going to settings -> iCloud -> iCloud Backup",
    "bored": "If you're bored, try going for a walk, reading, or completing a puzzle",
    "old is earth": "The Earth is 4.543 billion years old",
    "old is the earth": "The Earth is 4.543 billion years old",
    "is a meme": "A meme is an image or video, usually humorous, that is spead across the internet",
    "earth made": "The Earth was made 4.543 billion years ago",
    "aliens real": "As far as I know, aliens do not exist. However it is likely",
    "aliens exist": "As far as I know, aliens do not exist. However it is likely",
    "you worried about": "I am not worried about anything",
    "Write me an email": "Sorry, but I can't write an email",
    "write me an email": "Sorry, but I can't write an email",
    "Write an email": "Sorry, but I can't write an email",
    "Write an email": "Sorry, but I can't write an email",
    "assist me": "Assisting others is something I'm great at! Ask me anything and I'll help as best as I can",
    "Thanks": "You're welcome",
    "thanks": "You're welcome",
    "Thank you": "You're welcome",
    "thank you": "You're welcome",
    "directions": "Sorry, but I don't have access to mapping services",
    "map": "Sorry, but I don't have access to mapping services",
    "color is the sky": "The sky is blue",
    "color is grass": "Grass is usually green",
    "color is the sun": "The sun is yellow and orange",
    "color is water": "Water is clear but can appear blue",
    "color is the ocean": "The ocean is many shades of blue",
    "color is a tree": "A tree can be many colors depending on the type and season, but they are usually green",
    "color are trees": "A tree can be many colors depending on the type and season, but they are usually green",
    "What can you do": "I can do math, tell the date and time, tell a joke, a fact, and so much more",
    "what can you do": "I can do math, tell the date and time, tell a joke, a fact, and so much more",
    "digits of pi": "The first 12 digits of pi are 3.14159265359",
}